//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ALS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IALS_security")]
    public interface IALS_security
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IALS_security/getPrivilegiosXusuario", ReplyAction="http://tempuri.org/IALS_security/getPrivilegiosXusuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WCF_ALS.getPrivilegiosXusuarioResponse> getPrivilegiosXusuarioAsync(WCF_ALS.getPrivilegiosXusuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IALS_security/getSystemKeysXusuario", ReplyAction="http://tempuri.org/IALS_security/getSystemKeysXusuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WCF_ALS.getSystemKeysXusuarioResponse> getSystemKeysXusuarioAsync(WCF_ALS.getSystemKeysXusuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IALS_security/IsAuthenticated", ReplyAction="http://tempuri.org/IALS_security/IsAuthenticatedResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WCF_ALS.IsAuthenticatedResponse> IsAuthenticatedAsync(WCF_ALS.IsAuthenticatedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IALS_security/GetGroups", ReplyAction="http://tempuri.org/IALS_security/GetGroupsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WCF_ALS.GetGroupsResponse> GetGroupsAsync(WCF_ALS.GetGroupsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IALS_security/EmplIDfromDomainUser", ReplyAction="http://tempuri.org/IALS_security/EmplIDfromDomainUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WCF_ALS.EmplIDfromDomainUserResponse> EmplIDfromDomainUserAsync(WCF_ALS.EmplIDfromDomainUserRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class getPrivilegiosXusuarioResponseGetPrivilegiosXusuarioResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPrivilegiosXusuario", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getPrivilegiosXusuarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IDUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IDAplicacion;
        
        public getPrivilegiosXusuarioRequest()
        {
        }
        
        public getPrivilegiosXusuarioRequest(string IDUsuario, string IDAplicacion)
        {
            this.IDUsuario = IDUsuario;
            this.IDAplicacion = IDAplicacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPrivilegiosXusuarioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getPrivilegiosXusuarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WCF_ALS.getPrivilegiosXusuarioResponseGetPrivilegiosXusuarioResult getPrivilegiosXusuarioResult;
        
        public getPrivilegiosXusuarioResponse()
        {
        }
        
        public getPrivilegiosXusuarioResponse(WCF_ALS.getPrivilegiosXusuarioResponseGetPrivilegiosXusuarioResult getPrivilegiosXusuarioResult)
        {
            this.getPrivilegiosXusuarioResult = getPrivilegiosXusuarioResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class getSystemKeysXusuarioResponseGetSystemKeysXusuarioResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSystemKeysXusuario", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getSystemKeysXusuarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IDUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IDAplicacion;
        
        public getSystemKeysXusuarioRequest()
        {
        }
        
        public getSystemKeysXusuarioRequest(string IDUsuario, string IDAplicacion)
        {
            this.IDUsuario = IDUsuario;
            this.IDAplicacion = IDAplicacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSystemKeysXusuarioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getSystemKeysXusuarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WCF_ALS.getSystemKeysXusuarioResponseGetSystemKeysXusuarioResult getSystemKeysXusuarioResult;
        
        public getSystemKeysXusuarioResponse()
        {
        }
        
        public getSystemKeysXusuarioResponse(WCF_ALS.getSystemKeysXusuarioResponseGetSystemKeysXusuarioResult getSystemKeysXusuarioResult)
        {
            this.getSystemKeysXusuarioResult = getSystemKeysXusuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsAuthenticated", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsAuthenticatedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string domain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pwd;
        
        public IsAuthenticatedRequest()
        {
        }
        
        public IsAuthenticatedRequest(string domain, string username, string pwd)
        {
            this.domain = domain;
            this.username = username;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsAuthenticatedResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsAuthenticatedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool IsAuthenticatedResult;
        
        public IsAuthenticatedResponse()
        {
        }
        
        public IsAuthenticatedResponse(bool IsAuthenticatedResult)
        {
            this.IsAuthenticatedResult = IsAuthenticatedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGroups", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGroupsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string domain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pwd;
        
        public GetGroupsRequest()
        {
        }
        
        public GetGroupsRequest(string domain, string username, string pwd)
        {
            this.domain = domain;
            this.username = username;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGroupsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGroupsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetGroupsResult;
        
        public GetGroupsResponse()
        {
        }
        
        public GetGroupsResponse(string GetGroupsResult)
        {
            this.GetGroupsResult = GetGroupsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmplIDfromDomainUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EmplIDfromDomainUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string domain;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username;
        
        public EmplIDfromDomainUserRequest()
        {
        }
        
        public EmplIDfromDomainUserRequest(string domain, string username)
        {
            this.domain = domain;
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmplIDfromDomainUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EmplIDfromDomainUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EmplIDfromDomainUserResult;
        
        public EmplIDfromDomainUserResponse()
        {
        }
        
        public EmplIDfromDomainUserResponse(string EmplIDfromDomainUserResult)
        {
            this.EmplIDfromDomainUserResult = EmplIDfromDomainUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IALS_securityChannel : WCF_ALS.IALS_security, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ALS_securityClient : System.ServiceModel.ClientBase<WCF_ALS.IALS_security>, WCF_ALS.IALS_security
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ALS_securityClient() : 
                base(ALS_securityClient.GetDefaultBinding(), ALS_securityClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IALS_security.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ALS_securityClient(EndpointConfiguration endpointConfiguration) : 
                base(ALS_securityClient.GetBindingForEndpoint(endpointConfiguration), ALS_securityClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ALS_securityClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ALS_securityClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ALS_securityClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ALS_securityClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ALS_securityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCF_ALS.getPrivilegiosXusuarioResponse> WCF_ALS.IALS_security.getPrivilegiosXusuarioAsync(WCF_ALS.getPrivilegiosXusuarioRequest request)
        {
            return base.Channel.getPrivilegiosXusuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCF_ALS.getPrivilegiosXusuarioResponse> getPrivilegiosXusuarioAsync(string IDUsuario, string IDAplicacion)
        {
            WCF_ALS.getPrivilegiosXusuarioRequest inValue = new WCF_ALS.getPrivilegiosXusuarioRequest();
            inValue.IDUsuario = IDUsuario;
            inValue.IDAplicacion = IDAplicacion;
            return ((WCF_ALS.IALS_security)(this)).getPrivilegiosXusuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCF_ALS.getSystemKeysXusuarioResponse> WCF_ALS.IALS_security.getSystemKeysXusuarioAsync(WCF_ALS.getSystemKeysXusuarioRequest request)
        {
            return base.Channel.getSystemKeysXusuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCF_ALS.getSystemKeysXusuarioResponse> getSystemKeysXusuarioAsync(string IDUsuario, string IDAplicacion)
        {
            WCF_ALS.getSystemKeysXusuarioRequest inValue = new WCF_ALS.getSystemKeysXusuarioRequest();
            inValue.IDUsuario = IDUsuario;
            inValue.IDAplicacion = IDAplicacion;
            return ((WCF_ALS.IALS_security)(this)).getSystemKeysXusuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCF_ALS.IsAuthenticatedResponse> WCF_ALS.IALS_security.IsAuthenticatedAsync(WCF_ALS.IsAuthenticatedRequest request)
        {
            return base.Channel.IsAuthenticatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCF_ALS.IsAuthenticatedResponse> IsAuthenticatedAsync(string domain, string username, string pwd)
        {
            WCF_ALS.IsAuthenticatedRequest inValue = new WCF_ALS.IsAuthenticatedRequest();
            inValue.domain = domain;
            inValue.username = username;
            inValue.pwd = pwd;
            return ((WCF_ALS.IALS_security)(this)).IsAuthenticatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCF_ALS.GetGroupsResponse> WCF_ALS.IALS_security.GetGroupsAsync(WCF_ALS.GetGroupsRequest request)
        {
            return base.Channel.GetGroupsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCF_ALS.GetGroupsResponse> GetGroupsAsync(string domain, string username, string pwd)
        {
            WCF_ALS.GetGroupsRequest inValue = new WCF_ALS.GetGroupsRequest();
            inValue.domain = domain;
            inValue.username = username;
            inValue.pwd = pwd;
            return ((WCF_ALS.IALS_security)(this)).GetGroupsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCF_ALS.EmplIDfromDomainUserResponse> WCF_ALS.IALS_security.EmplIDfromDomainUserAsync(WCF_ALS.EmplIDfromDomainUserRequest request)
        {
            return base.Channel.EmplIDfromDomainUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCF_ALS.EmplIDfromDomainUserResponse> EmplIDfromDomainUserAsync(string domain, string username)
        {
            WCF_ALS.EmplIDfromDomainUserRequest inValue = new WCF_ALS.EmplIDfromDomainUserRequest();
            inValue.domain = domain;
            inValue.username = username;
            return ((WCF_ALS.IALS_security)(this)).EmplIDfromDomainUserAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IALS_security))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IALS_security))
            {
                return new System.ServiceModel.EndpointAddress("http://wcf_als.diunsa.hn/ALS_security.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ALS_securityClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IALS_security);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ALS_securityClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IALS_security);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IALS_security,
        }
    }
}
